### ISSUE TITLE
Builder UI does not show all builds of a single version

### ISSUE THREAD

**Issue by jvogt** [habitat-sh/on-prem-builder#167] opened 2019-07-31 22:35 UTC
Steps to Reproduce:
1) Visit https://bldr.habitat.sh/#/pkgs/chef/scaffolding-chef-inspec
2) Note current number of builds (at time of this issue, 32)
3) Select 0.12.0 to show the list of builds
4) Dropdown only shows 26 builds, and there is no notification of additional unshown builds, or mechanism to see them.

At minimum it would improve UX to display a message like, "Not showing x older builds"

**Comment by apriofrost** [comment] 2019-08-28 23:57
![image](https://user-images.githubusercontent.com/9401459/63900173-8c7fe900-c9b4-11e9-9203-f79a12d2a013.png)
See screenshot above for the mentioned package. There are three versions with the exact same identifier, all with duplicated channel names listed. Seems more like a technical issue than a UX issue.

**Comment by chefsalim** [comment] 2019-09-25 17:10
The root cause of this issue is the mechanism we are using to get the list of versions.
The version queries depend on complex Postgresql views. For example: 

```
CREATE OR REPLACE VIEW packages_with_channel_platform AS
    SELECT 
        op.id,
        op.owner_id,
        op.name,
        op.ident,
        op.ident_array,
        op.checksum,
        op.manifest,
        op.config,
        op.target,
        op.deps,
        op.tdeps,
        op.build_deps,
        op.build_tdeps,
        op.exposes,
        op.visibility,
        op.created_at,
        op.updated_at,
        op.origin,
        array_agg(oc.name) OVER w AS channels,
        array_agg(op.target) OVER w AS platforms
    FROM origin_packages op
    INNER JOIN origin_channel_packages AS ocp ON op.id = ocp.package_id
    INNER JOIN origin_channels AS oc ON oc.id = ocp.channel_id
    WINDOW w AS (PARTITION BY op.ident);
```

The `packages_with_channel_platforms` view not only joins two other tables, but also does two array aggregations over window partitions.

The upshot of this is that the query can (and does) return multiple repeated rows that then need to be de-duplicated before passing the results back to the caller.

However this means that we cannot do proper range queries on the view - so when we, for example, specify that we want 50 rows, we have to make multiple queries until we actually get 50 unique rows.
This is not a clean or scalable solution. 

Furthermore, there are other issues related to the use of views. In the `origin_package_versions` view we also group by the visibility, which also results in multiple rows that make the UI show two different sets of packages for the same version.

Finally, the view performance, while greatly improved over the query fan-out we had previously, is also degraded over time as the number of channels increase.

For those reasons, we will need to investigate moving away from the current channel and platform views design, and instead consider de-normalizing the channels data for a better fix.

**Comment by sajjaphani** [comment] 2022-03-23 03:54
Closing the issue as it's resolved here https://github.com/habitat-sh/builder/issues/1615. Reopen if necessary.

**Closed by sajjaphani** 2022-03-23 03:54 UTC
Labels: C-bug, V-bldr, A-builder
